
spring:

  # ORM config
  jpa:
    hibernate:
      ddl-auto: create

  # MySQL config
  datasource:
    url: jdbc:mysql://localhost:3306/minsDB
    username: testUser
    password: test!123123
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # Redis config
  redis:
    host: mins-redis.2dyjoo.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

#  # MongoDB
#  data:
#    mongodb:
#      host: docdb-2019-10-20-11-14-37.cpfhuqglxhri.ap-northeast-2.docdb.amazonaws.com
#      port: 27017
#      username: minsMongoDB2
#      password: test1234
#      database: admin

server:
  port: 18080